dist: trusty
sudo: required
language: ruby
install:
  - sudo pip install requests lxml cssselect
  - bundle install
script:
  - bundle exec jekyll build
  - pwd
  - ls
  - ls _site
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
