dist: trusty
sudo: required
install:
- sudo pip install requests lxml cssselect
- sudo bundle install
script:
- bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: AKIAJARHEWIMW6AEM2RA
  secret_access_key:
    secure: bszJ5DQfUIlgEKBHs4dSy5V0P3h5geaRKcXKGflNNGFpAaUr/wbAGqLgBCrbC7mIiVGzTJeNVHFvlDZlDkeOfoFe1+tXvrK4HgtCFBp8a+NJa587jMNY3C1wkIE+yuz6p8rapKiLGOxxP8wzb4awj0y9x77tefsbQo0gc5XkmIUK1XVpxWT02RMPENaGAVs7HZkaIVx4eU9ipdXzDsNfVoeeAiKyCGEQFeUZsWHw/ma1kKG8XAc15zUaSjViIq3MxlaO+o5k5W73xk+cg5VcehJrWhSklkzPX8U1oFWBpnHaS5xAVKchAdKtvxvXfvPoKsW83trM/2E6zxjTsM+Uv4Dg0BiewERAheVmdBr0eBieOG0/kDTwXcd26goHh7tprP1tT37XskkX8xxbFrQvlRDAZSC0X5au62NzPwF732X1XJR2UotWP69qNG62r+tR1beD5EmMbkqs9JAp3LZ+p1GohoVK8PNYh6DJvNSV49jI9cAI3v1h3LFSSMLaOgrccb8FpYbgrLJZ4uJu+PuI3XCBZVKEXGyekyn3gRFdZVG+lheEPxRd+0lUmYMkU3PqH9zniOgMtMniQBB9wE09wpmSglNNLDhboa7GnG+zAevB5MldCk0rUs/oDBfi8OJP8aaGRbtUNkZSdqpUrYM5eVlOnSrNF24Vyy4Rl0nFPTU=
  bucket: selenium.ru
  local-dir: _site
  acl: public_read
  on:
    repo: barancev/selenium.ru
