- menu_name: "Связь"

- name: "Контакты"
  url: "/contact/"
  title: "Контакты"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"
